version: '3.2'
services:
  sql-server-db:
    container_name: event-tracker-sql-server
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - '1434:1433'
    environment:
      SA_PASSWORD: 'Docker_SQL_#Password_&'
      ACCEPT_EULA: 'Y'